bitstarter/urls.py
from django.conf.urls import url, patterns
from django.views.generic import TemplateView
from .views import BitstarterView

urlpatterns = patterns(
    '',
    url(r'^$', BitstarterView.as_view(), name='home'),
)

coinbase/urls.py
from django.conf.urls import patterns, include, url
from .views import *

urlpatterns = patterns(
    '',
    url(r'^balance$', 'coinbase.views.balance'),
    url(r'^orders$', 'coinbase.views.orders'),
    url(r'^sell$', 'coinbase.views.sell'),
    url(r'^cfbox$', CrowdfundingBoxStat.as_view(), name='box'),
    url(r'^orderlist$', CrowdfundingOrderList.as_view(), name='orders'),
)

contact_messages/urls.py
from django.conf.urls import url, patterns
from .views import MessageCreateView, MessageListView

urlpatterns = patterns(
    '',
    url(r'^add/$', MessageCreateView.as_view(), name='add'),
    url(r'^$', MessageListView.as_view(), name='list'),
)

mindinbox/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', include('bitstarter.urls', namespace='bitstarter')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^cb/', include('coinbase.urls', namespace='coinbase')),
    url(r'^contact_messages/', include('contact_messages.urls', namespace="contact_messages")),
)

urlpatterns += patterns(
    '',
    (r'^static/(.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT}),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

coinbase/models.py
""" Coinbase API model

    Provides access to coinbase wallet.

    API version 1.0

    https://coinbase.com/api/doc

    API Key must be enabled, see:
        https://coinbase.com/account/integrations
"""
from os import environ
from aniso8601 import parse_datetime
from time import strftime
from urllib.request import urlopen, build_opener, install_opener
import json


class CoinbaseWallet(object):
    @staticmethod
    def secret_key():
        return environ['COINBASE_API_KEY']

    @staticmethod
    def get_json_data(request, **kwargs):
        opener = build_opener()
        opener.addheaders = [('User-agent', 'Mozilla/5.0')]
        install_opener(opener)
        url = 'https://coinbase.com/api/v1/{0}?api_key={1}'
        url = url.format(request, CoinbaseWallet.secret_key())
        for k in kwargs:
            url += '&{0}={1}'.format(k, kwargs[k])
        data = urlopen(url).read().decode('utf-8')
        return json.loads(data)

    @staticmethod
    def balance():
        return CoinbaseWallet.get_json_data('account/balance')

    @staticmethod
    def orders():
        orders = CoinbaseWallet.get_json_data('orders')['orders']
        orders_list = []
        for x in orders:
            x = x['order']
            coins = int(x['total_btc']['cents'])/100000000.0
            dt = parse_datetime(x['created_at']).utctimetuple()
            ds = strftime("%a, %d %b %Y", dt)
            ts = strftime("%H:%M:%S", dt)
            if x['status'] == 'completed':
                orders_list.append([x['id'], coins, ds, ts])
        return orders_list

    @staticmethod
    def get_orders_count():
        return len(CoinbaseWallet.orders()) 

    @staticmethod
    def sell(count):
        return CoinbaseWallet.get_json_data('prices/sell', qty=count)

    @staticmethod
    def get_total_USD():
        balance = CoinbaseWallet.balance()
        total = 0.0
        if balance['currency'] == 'BTC':
            balance = CoinbaseWallet.sell(balance['amount'])['total']
        if balance['currency'] == 'USD':
            total += float(balance['amount'])
        return max(0, total)

contact_messages/models.py
from django.db import models


class Message(models.Model):
    sender_IP = models.IPAddressField(blank=True, default='127.0.0.1')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    user_name = models.CharField(max_length=255, blank=True, default='')
    user_email = models.EmailField(blank=True, default='')
    content = models.TextField()

bitstarter/views.py
from django.views.generic.base import TemplateView
from datetime import datetime
from coinbase.models import CoinbaseWallet
from django.conf import settings

class BitstarterView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super(BitstarterView, self).get_context_data(**kwargs)
        context['debug'] = settings.DEBUG
        return context

coinbase/views.py
# Create your views here.
from django.views.generic.base import TemplateView
from datetime import datetime
from django.http import HttpResponse
from .models import CoinbaseWallet


def balance(request):
    return HttpResponse("Balance $%s." % CoinbaseWallet.get_total_USD())


def orders(request):
    return HttpResponse("Orders %s." % CoinbaseWallet.orders())


def sell(request):
    return HttpResponse("Sell %s." % CoinbaseWallet.sell(100))


class CrowdfundingBoxStat(TemplateView):
    template_name = "statbox.html"

    def get_context_data(self, **kwargs):
        context = super(TemplateView, self).get_context_data(**kwargs)
        context['start_date'] = datetime(2013, 12, 21)
        context['backers_count'] = CoinbaseWallet.get_orders_count()
        current_donations = CoinbaseWallet.get_total_USD()
        total_sum = 300000
        done = current_donations * 100 / total_sum
        context['current_balance'] = current_donations
        context['total_sum'] = total_sum
        context['done_percent'] = done
        context['rest_percent'] = 100 - done
        return context

class CrowdfundingOrderList(TemplateView):
    template_name = "orderlist.html"

    def get_context_data(self, **kwargs):
        context = super(TemplateView, self).get_context_data(**kwargs)
        context['orders'] = CoinbaseWallet.orders()
        return context

contact_messages/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from .models import Message


class MessageListView(ListView):
    model = Message


class MessageDetailView(DetailView):
    model = Message


class MessageCreateView(CreateView):
    model = Message

bitstarter/templates/addons/external.html
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

bitstarter/templates/addons/menu.html
<div class="navbar navbar-inverse navbar-fixed-top" id="navbar">
    <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'bitstarter:home' %}">Thinking In Box</a>
        <div class="nav-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#dashboard">Home</a></li>
                <li><a href="#mission">Our mission</a></li>
                <li><a href="#how-it-works">How it works</a></li>
                <li><a href="#features">Features</a></li>
                <li><a href="#roadmap">Roadmap</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
	$('a[href^="#"]').on('click', function(e) {
		e.preventDefault();
		hash = $(this).prop('hash');
		console.log(hash);
		$('html, body').animate({
		    'scrollTop': $(hash).offset().top - $('.navbar-fixed-top').height()
		}, 2000);
	});
    });
</script>

bitstarter/templates/index.html
{% extends '_layouts/base.html' %}

{% block page_title %}Bitstarter{% endblock %}

{% block page_styles %}
	<meta property="fb:admins" content="100006490210703" />
    <link href='{{ STATIC_URL }}css/bitstarter/main.css' rel='stylesheet' type='text/css'>
    <link href='{{ STATIC_URL }}css/bitstarter/dashboard.css' rel='stylesheet' type='text/css'>
    <link href='{{ STATIC_URL }}css/bitstarter/mission.css' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Pathway+Gothic+One&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,100italic,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
{% endblock %}

{% block page_scripts %}
    <script src="{{ STATIC_URL }}js/jquery.tinyscrollbar.min.js"></script>
    <script src="{{ STATIC_URL }}js/waypoints.min.js"></script>
{% endblock %}

{% block page_content %}
<body data-spy="scroll" data-target="#navbar" data-offset=70>
{% include 'addons/menu.html' %}
{% include 'addons/external.html' %}
{% include 'sections/dashboard.html' %}
{% include 'sections/mission.html' %}
{% include 'sections/at-a-glance.html' %}
{% include 'sections/features.html' %}
{% include 'sections/source-code.html' %}
{% include 'sections/mobile.html' %}
{% include 'sections/sandbox.html' %}
{% include 'sections/roadmap.html' %}
{% include 'sections/contact.html' %}
<footer class="row-spacer">
<div class="container center">
    <div class="copyright">© 2013 Thinking In Box</div>
</div>
</footer>
</body>
{% endblock %}

{% block end_scripts %}
<script src="{{ STATIC_URL }}js/bitstarter.js"></script>
{% endblock %}

bitstarter/templates/sections/contact.html
<section id="contact">
    <label>Contact Us</label>
    <div class="container">
        <div class="row">
            <div class="col-lg-5" id="send-message">
                <h3 class="subheader">Leave a message</h3>
                <p class="text-danger">Sorry, messages are under construction yet. Use social networks to contact us.</p>
                <form id="contact-form" action="post">
                    <input type="text" class="form-control" id="username" name="username" placeholder="Your name">
                    <input type="text" class="form-control" id="email" name="email" placeholder="Your email">
                    <textarea class="form-control" rows="5" placeholder="Your message"></textarea>
                    {% comment %}
                    <button type="button" class="btn btn-default pull-right btn-lg">Send</button>
                    {% endcomment %}
                </form>
            </div>
            <div class="col-lg-2" id="social-links">
                <h3 class="subheader">Say Hello</h3> 
                <a href="https://www.facebook.com/pages/Thinking-In-Box/356419494489877">
                   <i class="icon-facebook-sign"></i>
                </a>
                <a href="https://plus.google.com/101018259054761270486" rel="publisher">
                   <i class="icon-google-plus-sign"></i>
                </a> 
                <a href="https://twitter.com/ThinkingInBox">
                    <i class="icon-twitter-sign"></i>
                </a>
            </div>
            <div class="col-lg-5" id="read-us">
                <h3 class="subheader">Add comments</h3> 
                <div class="fb-comments" data-href="http://thinking-in-box.herokuapp.com/" data-colorscheme="dark" data-width="400"></div>                
            </div>
        </div>
    </div>
</section>

bitstarter/templates/sections/dashboard.html
<section id="dashboard">
    <div>
        <div class="dashboard">
            <div class="box box-s logo dash-col-1 dash-row-2">THINKING IN BOX</div> 
            <div class="box box-s dash-col-1 dash-row-1 box-purple">
                <div class="header">
                    Our Mission
                </div>
                <div class="cover">
                    <p>Who we are and what your goals</p> 
                    <a href="#mission" class="link">
                        <i class="icon-double-angle-down icon-large"></i>
                    </a>
                </div>
            </div>
            <div class="box box-s dash-col-2 dash-row-1 box-light-green">
                <div class="header">At a glance</div>
                <div class="cover">
                    <p>What is the box<br>How it works</p>
                    <a href="#at-glance" class="link">
                        <i class="icon-double-angle-down icon-large"></i>
                    </a>
                </div>
            </div>
            <div class="box box-s dash-col-3 dash-row-1 box-red">
                <div class="header">Features</div>
                <div class="cover">
                    <p>Features and tool what our service will prodive</p>
                    <a href="#features" class="link">
                        <i class="icon-double-angle-down icon-large"></i>
                    </a>
                </div>
                <div class="back">
                    <p class="attention">Beware of falling boxes!</p>
                    <p> Sorry, this site part isn't ready yet</p>
                    <p> We work hard to finish it as soon as possible</p>
                </div>
            </div>
            <div class="box box-x3 dash-col-4 dash-row-1 box-white" id="crowdfunding-box">
                <div class="header">
                    <p>Crowdfunding</p>
                    <p class="header-comment">Everyone can help</p>
		            <div data-toggle="modal" href="#orderModal" class="button">donation list</div>
                </div>
                <div class="cover">
                    <div class="row center" id='funding-stat'>
                        <div style="height: 120px; text-align: center; padding-top: 50px">
                            <i class="icon-spinner icon-spin icon-large"></i> updating...
                        </div>
                    </div>
                    <div class="row center">
                        <div class="donate-button">
                              <a class="coinbase-button" data-code="f35dfbc887825113329bbefed578450f" data-button-style="custom_small" href="https://coinbase.com/checkouts/f35dfbc887825113329bbefed578450f">Donate Bitcoins</a><script src="https://coinbase.com/assets/button.js" type="text/javascript"></script>
                        </div>
                    </div>
                    <div class="row center"><h5>or<br>share us</h5></div>
                    <div class="row center">
                        <div class="col-lg-10 col-lg-offset-1">
                            <!-- AddThis Button BEGIN -->
                            <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
                                <a class="addthis_button_facebook"></a>
                                <a class="addthis_button_twitter"></a>
                                <a class="addthis_button_google_plusone_share"></a>
                                <a class="addthis_button_linkedin"></a>
                                <a class="addthis_button_pinterest_share"></a>
                                <a class="addthis_button_compact"></a><a class="addthis_counter addthis_bubble_style"></a>
                            </div>
                            <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
                            <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5204e4990d86bd7b"></script>
                            <!-- AddThis Button END -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="box box-s dash-col-3 dash-row-2 box-light-blue">
                <div class="header">Source code</div>
                <div class="cover">
                    <p>Open service with open source code</p>
                    <a href="#source-code" class="link">
                        <i class="icon-double-angle-down icon-large"></i>
                    </a>
                </div>
            </div>
            <div class="box box-s dash-col-1 dash-row-3 box-green">
                <div class="header">Mobile</div>
                <div class="cover">
                    <p>Your thoughts are with you always and everywhere</p>
                    <a href="#mobile" class="link">
                        <i class="icon-double-angle-down icon-large"></i>
                    </a>
                </div>
            </div>
            <div class="box box-s dash-col-2 dash-row-3 box-orange">
                <div class="header">Sandbox</div>
                <div class="cover">
                    <p>Easy to try</p>
                    <a href="#sandbox" class="link">
                        <i class="icon-double-angle-down icon-large"></i>
                    </a>
                </div>
            </div>
            <div class="crowdfunding-footer-arrow dash-col-4 dash-row-3">
                <img src="{{ STATIC_URL }}img/cf-footer.png">
            </div>
            {% comment %}
            {% endcomment %}
            <div class="box box-s dash-col-3 dash-row-3 box-dark-gray">
                <div class="header">Roadmap</div>
                <div class="cover">
                    <p>Long, long way to goal</p>
                    <a href="#roadmap" class="link">
                        <i class="icon-double-angle-down icon-large"></i>
                    </a>
                </div>
            </div>
            <div class="social-row">
                <div class="social-button">
                    <div class="fb-like" data-href="http://thinking-in-box.herokuapp.com/" data-width="450" data-layout="button_count" data-show-faces="false" data-send="false"></div>
                </div>
                <div class="social-button">
                    <div class="g-plusone" data-size="standard" data-annotation="bubble" data-width="450" data-href="http://thinking-in-box.herokuapp.com/" data-align="right"></div>
                    <script type="text/javascript">
                      window.___gcfg = {lang: 'ru'};

                      (function() {
                        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                        po.src = 'https://apis.google.com/js/plusone.js';
                        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                      })();
                    </script>
                </div>
                <div class="social-button">
                    <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://thinking-in-box.herokuapp.com/" data-via="ThinkingInBox">Tweet</a>                
                </div>
            </div>
	    </div>
    </div>
</section>
<div class="modal fade" id="orderModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Donation list</h4>
      </div>
      <div class="modal-body">
	<div style="text-align: center; min-height: 200px; padding-top: 80px;">
          <i class="icon-spinner icon-spin icon-large"></i> updating...
	</div>
      </div>
      <div class="modal-footer">
	<div class="row pull-left" style="float: left">
           <b>You also want to take part of the project?</b> 
           <p>You can make a donation, or tell about us in social networks</p>
        </div>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
    $(document).ready(function() {
        $('#funding-stat').load('{% url 'coinbase:box' %}');
    });

    $('#orderModal').on('show.bs.modal', function () {
	$(this).find('.modal-body').load('{% url 'coinbase:orders' %}');
    });

    /* Set dashboard height depends of window size */
    function FixDashboardSectionSize () {
        h = Math.max($(window).height(), $('.dashboard').height() + 180);
        $('#dashboard').css({height: h});
    }

    $(window).resize(FixDashboardSectionSize);
    $(document).ready(FixDashboardSectionSize);
</script>

bitstarter/templates/sections/features.html
<section class="section-even" id="features">
    <label>Features</label>
    <div class="container">
        <h2 class="slogan">What we plan to do to help you</h2>
        <div class="under-construction center">
            <div>This section is under construction now.</div>
            <div>We are currently working on a list of planned features and prepare their detailed description,<br> as well as on the voting system to select the most useful.</div>
            <div>Follow us to keep abreast of changes</div>
        </div>
        {% comment %}
        <h4>Here the list of some features</h4>
        <ul class="icons-ul">
            <li><i class="icon-li icon-ok-circle"></i>Ideas box</li>
            <li><i class="icon-li icon-ok-circle"></i>Brainstorming</li>
            <li><i class="icon-li icon-ok-circle"></i>Goal tracking</li>
            <li><i class="icon-li icon-ok-circle"></i>Task box</li>
            <li><i class="icon-li icon-ok-circle"></i>Check list</li>
            <li><i class="icon-li icon-ok-circle"></i>Calendar</li>
            <li><i class="icon-li icon-ok-circle"></i>Plan</li>
            <li><i class="icon-li icon-ok-circle"></i>Workflow</li>
            <li><i class="icon-li icon-ok-circle"></i>Dashboard</li>
            <li><i class="icon-li icon-ok-circle"></i>Product/features rates</li>
            <li><i class="icon-li icon-ok-circle"></i>User comments</li>
            <li><i class="icon-li icon-ok-circle"></i>Virtual box</li>
            <li><i class="icon-li icon-ok-circle"></i>Wareframing box</li>
            <li><i class="icon-li icon-ok-circle"></i>Workspace</li>
            <li><i class="icon-li icon-ok-circle"></i>etc.</li>
        </ul>
        {% endcomment %}
    </div>
</section>

bitstarter/templates/sections/mission.html
<section id="mission">
	<label>mission</label>
    <h2 class="slogan">Make a way from dream to reality easier</h2>
    <div id="carousel-mission" class="carousel slide carousel-fade" data-interval=5000>
	    <div class="carousel-indicators">
	        <div class="indicator green position-1 active" data-target="#carousel-mission" data-slide-to="0">
	            <div class="cover"></div>
	            <div class="caption" style="padding-top: 33px">Think</div>
	        </div>
	        <div class="indicator orange position-2" data-target="#carousel-mission" data-slide-to="1">
	            <div class="cover"></div>
	            <div class="caption">Manage the life</div>
	        </div>
	        <div class="indicator purple position-3" data-target="#carousel-mission" data-slide-to="2">
	            <div class="cover"></div>
	            <div class="caption">Save the time</div>
	        </div>
	        <div class="indicator red position-4" data-target="#carousel-mission" data-slide-to="3">
	            <div class="cover"></div>
	            <div class="caption">Work together</div>
	        </div>	        
	        <div class="indicator blue position-5" data-target="#carousel-mission" data-slide-to="4">
	            <div class="cover"></div>
	            <div class="caption" style="padding-top: 33px">Personal</div>
	        </div>
		</div>
	    <!-- Wrapper for slides -->
		<div class="carousel-inner">
		    <div class="item active" id="mission-think-slide">
		    	<div class="item-box"></div>
		    	<div class="background"></div>
		    	<p class="caption green">Think</p>
		    	<p class="comment middle">We believe that it all starts<br> with a thought and better thoughts<br> lead to better results.</p>
		    	<p class="comment big green" style="width: 350px">We create and connect together tools <br> for storing your ideas and work on them.</p>		    	
		    	<p class="comment" style="padding-top: 20px;">Using boxes and special tools, such as mind maps<br> and brainstorming, you can improve your ideas,<br> focus on details, share them with others<br>to work together towards<br> a common goal.</p>		    	
		    </div>
		    <div class="item" id="mission-life-slide">
		    	<div class="item-box"></div>
		    	<div class="background"></div>
	    		<p class="caption orange">Manage<br>the life</p>
	    		<p class="comment middle">Taking the activities under control</p>
	    		<p class="comment big orange" style="width: 350px">We want to make easier goal setting,<br>work planning and tracking progress.</p>    		
	    		<div class="comment" style="padding-top: 20px">
	    			We will provide solutions that helps you:<br>
	    			<i class="icon-angle-right"></i> plan you work<br>
	    			<i class="icon-angle-right"></i> follow right direction<br>
	    			<i class="icon-angle-right"></i> efficiently choose the next step<br>
	    			<i class="icon-angle-right"></i> monitor your actions.<br>
	    		</div>	    		
		    </div>
		    <div class="item" id="mission-time-slide">
		    	<div class="item-box"></div>
		    	<div class="background"></div>
	    		<p class="caption purple" style="margin-top: 60px">Save<br>the time</p>
	    		<p class="comment big purple">We can not give you more time,<br> but we can help to keep available.</p>	    		
	    		<p class="comment">
	    			We develop the tools for time management, that help you do what is really matters, reduce the cost of supporting tasks, work less and do more,<br> save time for more important things for you.
	    		</p>	    		
	    		<p class="comment" style="margin-top: -20px">
	    			At the same time our goal is to make the work<br> with the service as quickly as possible.<br> So that all the necessary commands<br> you could do in one click.
	    		</p>	    		
		    </div>
		    <div class="item" id="mission-together-slide">
		    	<div class="item-box"></div>
		    	<div class="background"></div>
	    		<p class="caption red">Work together</p>
	    		<p class="comment middle">Connect people thoughts and skills</p>
	    		<p class="comment big red">We create network for ideas, goals, projects and tasks<br> to help you move faster, lead to a better results.</p>
	    		<p class="comment">
	    			We want to make it easier to share ideas, to work together<br> toward common goals, to use the best opportunities<br> of each person for better results.
	    		</p>
	    		<p class="comment">
	    			We are creating a place where<br>it is only important<br> what you think<br> and do.
	    		</p>	    		
		    </div>		    		    
		    <div class="item" id="mission-personal-slide">
		    	<div class="item-box"></div>
		    	<div class="background"></div>
	    		<p class="caption blue">Personal</p>
	    		<p class="comment middle">Little piece of your own world</p>
	    		<p class="comment big blue" style="width: 350px; padding-top: 30px">
	    			For us it is important that<br>our users feel comfortable and free.<br>
	    			We make workspace for you<br> that helps focus on current task.
	    		</p>
	    		<p class="comment">Collect all information and tools that you need,<br> throw away all the unnecessary.<br>Clean your mind, there is only you<br> and your work - nothing more.</p>
		    </div>
		</div>  
    </div>
</section>

bitstarter/templates/sections/mobile.html
<style>
    .mockup-device {
        position: absolute;
        left: 0;
        right: 0;
        top: 30px;
        margin-left: auto;
        margin-right: auto;
        border-color: rgba(255, 255, 255, 1);
        border-style: solid;
        overflow: hidden;
        border-radius: 20px;
        -webkit-animation-name: 'switch-device';
        -webkit-animation-duration: 5s;
        -webkit-animation-iteration-count: infinite;
        -webkit-animation-timing-function: ease-in-out;
        -webkit-transform-style: preserve-3d;
        -moz-animation-name: 'switch-device';
        -moz-animation-duration: 5s;
        -moz-animation-iteration-count: infinite;
        -moz-animation-direction: alternate;
        -moz-animation-timing-function: ease-in-out;
        -moz-transform-style: preserve-3d;
        -ms-animation-name: 'switch-device';
        -ms-animation-duration: 5s;
        -ms-animation-iteration-count: infinite;
        -ms-animation-direction: alternate;
        -ms-animation-timing-function: ease-in-out;
        -ms-transform-style: preserve-3d;
        animation-name: 'switch-device';
        animation-duration: 5s;
        animation-iteration-count: infinite;
        animation-direction: alternate;
        animation-timing-function: ease-in-out;
        transform-style: preserve-3d;
    }
    
    @-webkit-keyframes 'switch-device' {
        from {
            width: 155px;
            height: 310px;
            border-width: 40px 10px;
            background: url({{ STATIC_URL }}img/mobile-phone-bkg.png) no-repeat;
            -webkit-transform: rotateY(0deg);
        }
        25% {
            -webkit-transform: perspective(600px) rotateY(105deg);
        }
        50% {
            width: 417px;
            height: 321px;
            border-width: 36px 31px;
            background: url({{ STATIC_URL }}img/mobile-tablet-bkg.png) no-repeat;
            -webkit-transform: rotateY(180deg);
        }
        75% {
            -webkit-transform: perspective(600px) rotateY(280deg);
        }
        to {
            width: 155px;
            height: 310px;
            border-width: 40px 10px;
            background: url({{ STATIC_URL }}img/mobile-phone-bkg.png) no-repeat;
            -webkit-transform: rotateY(360deg);
        }
    }

</style>
<section class="section-even" id="mobile">
    <label>Mobile</label>
    <div class="container">
        <h2 class="slogan">Your thoughts are with you always and everywhere</h2>
        <div class="row">
            <div class="col-lg-6">
                <ul class="icons-ul feature-details">
                    <li><i class="icon-li icon-ok-circle"></i>Autosync for all connected devices</li>
                    <li><i class="icon-li icon-ok-circle"></i>Offline access</li>
                    <li><i class="icon-li icon-ok-circle"></i>Quick add notes</li>
                    <li><i class="icon-li icon-ok-circle"></i>Task reminder</li>
                    <li><i class="icon-li icon-ok-circle"></i>Geo reminder</li>
                    <li><i class="icon-li icon-ok-circle"></i>All web tools in your device</li>
                </ul>
            </div>
            <div class="col-lg-6">
                <div class="mockup-device">
                </div>
            </div>
        </div>
        <div class="row platforms">
            <div class="col-lg-2 col-lg-offset-2"><i class="icon-android icon-5x"></i></div>
            <div class="col-lg-2 col-lg-offset-1"><i class="icon-apple icon-5x"></i></div>
            <div class="col-lg-2 col-lg-offset-1"><i class="icon-html5 icon-5x"></i></div>
        </div> 
    </div>
</section>

coinbase/templates/orderlist.html
<style>
	.table thead > tr > th {
		vertical-align: middle;
		text-align: center;
	}
</style>
<table class="table table-hover">
	<thead>
		<tr>
			<th rowspan=2>Coinbase Order ID</th>
			<th rowspan=2>BTC</th>
			<th colspan=2>Transaction</th>
		</tr>
		<tr>
			<th>Date</th>
			<th>Time (UTC)</th>
		</tr>
	</thead>
	{% for x in orders %}
	<tr>
		<td>{{ x.0 }}</td>
		<td>{{ x.1 }}</td>
		<td>{{ x.2 }}</td>
		<td>{{ x.3 }}</td>
	</tr>
	{% endfor %}
</table>